# Generated by Django 4.1 on 2022-08-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null='True', upload_to='uploads/'),
            preserve_default='True',
        ),
    ]
